upstream app {
    server app:8000;
}


server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://web:;
        proxy_set_header Host $host;
}

    # REST API (FastAPI) — доступен по /api/
    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://app;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Swagger UI FastAPI — напрямую
    location /docs {
        proxy_pass http://app/docs;
        proxy_set_header Host $host;
    }
    location /openapi.json {
        proxy_pass http://app/openapi.json;
    }

    location /health {
        proxy_pass http://app/health;
        access_log off;
    }

    location /auth/ {
        proxy_pass http://app/auth/;
    }

    location /balance/ {
        proxy_pass http://app/balance/;
    }

    location /predict/ {
        proxy_pass http://app/predict/;
    }

    location /history/ {
        proxy_pass http://app/history/;
        proxy_set_header Host $host;
    }
}
