version: "3.9"

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    volumes:
      - ./app/src:/app/src
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    expose:
      - "8000"
    restart: unless-stopped

  web-proxy:
    build:
      context: .           # контекст — корень проекта, чтобы достать frontend/
      dockerfile: web-proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ml_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ml_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./app/src:/app/src
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_QUEUE: ml_tasks
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ml_service
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 2
    restart: on-failure

volumes:
  postgres_data:
  rabbitmq_data:
